### PR TITLE
Uses dor services client to check if a new version can be opened.

### LINKED ISSUE #329: [hydrus/stage] RuntimeError: Cannot perform action: object_type=Item, action=open_new_version, pid=druid:md171sq2635.
Item is not accessioned
## Backtrace

    line 173 of [PROJECT_ROOT]/app/models/hydrus/item.rb: open_new_version
    line 295 of [PROJECT_ROOT]/app/controllers/hydrus_items_controller.rb: open_new_version

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/49897/faults/49762018)

### PR DESCRIPTION
**Pull request by justinlittman**
closes #329

### CODE REVIEW

**Comment by justinlittman** [comment]
@aaron-collier This is ready for a final review.

File: app/models/hydrus/processable.rb [hunk 1]
```diff
@@ -64,24 +64,12 @@ def should_start_assembly_wf
...
-    # accessioned lifecyle is set in the last step in the accessionWF.
-    return false unless workflow_client.lifecycle(REPO, pid, 'accessioned')
-
-    # Return false if accessionWF has been started for most current version and there are there are any incomplete workflow steps.
-    return false if workflow_client.active_lifecycle(REPO, pid, 'submitted')
-
-    # Accessioned.
-    true
+    # For testing, this avoids Dor::Services::Client.
+    return false if should_treat_as_accessioned
```
Comment (jcoyne) [inline app/models/hydrus/processable.rb]: I'm not asking for this now, but could we instead have changed all the tests to stub the client so that `openeable?` returned false? I'm just trying to understand the conditional.
