### PR TITLE
default collection objects to have world access

### LINKED ISSUE #478: New Hydrus APOs are being created with defaultObjectRights set to "discover"="none", which should never happen
Reported by @hannahfrost and @amyehodge:

New Hydrus APOs are being created with defaultObjectRights that should be impossible in Hydrus. Specifically, Hydrus objects should never have "discover" set to "none". 

```xml
<rightsMetadata>
  <access type="discover">
    <machine>
      <none/>
    </machine>
  </access>
  <access type="read">
    <machine>
      <world/>
    </machine>
  </access>
  <use>
    <human type="useAndReproduction">User agrees that, where applicable, content will not be used to identify or to otherwise infringe the privacy or confidentiality rights of individuals. Content distributed via the Stanford Digital Repository may be subject to additional license and use restrictions applied by the depositor.</human>
  </use>
  <copyright>
    <human/>
  </copyright>
</rightsMetadata>
```

Example druid: https://argo.stanford.edu/view/druid:fc704jq2575

**Impact**

The defaultObjectRights get applied to all new collections and items under that APO, so the result is that these incorrect rights are applied to all items within that collection/APO.

**Expected behavior**

The defaultObjectRights for Hydrus objects are set via the Hydrus collection form, which gives choices to make items world or stanford. The steps seem to be:

1. Create or edit a Hydrus collection
2. Behind the scenes a Hydrus APO is created or modified that uses the settings from the collection form
3. Collection and items get rights from the Hydrus APO

### PR DESCRIPTION
**Pull request by ndushay**
~~Hold until it's clear these are the correct default permissions.~~ Andrew signed off in slack

## Why was this change made?

Fixes #478 - new Hydrus collections have been created with incorrect default permissions for some time now.

## How was this change tested?

on stage; also wrote a test

### CODE REVIEW

**Review by jcoyne — APPROVED** [review]

File: app/models/hydrus/generic_object.rb [hunk 1]
```diff
@@ -312,7 +312,7 @@ def self.dor_registration_params(user_string, obj_typ, apo_pid)
 
       params[:administrative][:partOfProject] = 'Hydrus' unless obj_typ == 'adminPolicy'
       params[:identification] = { sourceId: "Hydrus:#{obj_typ}-#{user_string}-#{HyTime.now_datetime_full}" } if obj_typ == 'item'
-      params[:access] = {} if obj_typ == 'collection'
+      params[:access] = { 'access': 'world' } if obj_typ == 'collection'
```
Comment (mjgiarlo) [inline app/models/hydrus/generic_object.rb:315]: This is very minor, but can you change `'access':` to `access:` so it looks like a garden-variety symbolized hash?

File: spec/models/hydrus/generic_object_spec.rb [hunk 2]
```diff
@@ -67,13 +67,21 @@
     let(:args) { %w(whobar item druid:bc123df4567) }
 
     it 'returns the expected hash' do
-      puts dor_registration_params
```
Comment (mjgiarlo) [inline spec/models/hydrus/generic_object_spec.rb:70]: :tada:

File: app/models/hydrus/generic_object.rb (hunk 1 above)
Comment (ndushay) [reply app/models/hydrus/generic_object.rb:315]: it was choking but maybe I wrote my test wrong - will take a look.

File: spec/models/hydrus/generic_object_spec.rb [hunk 3]
```diff
@@ -67,13 +67,21 @@
...
       expect(dor_registration_params[:administrative][:partOfProject]).to eq('Hydrus')
       expect(dor_registration_params[:identification][:sourceId]).to start_with('Hydrus:item-whobar-')
+      expect(dor_registration_params[:access]).to eq nil
+    end
+
+    context 'when collection object' do
+      let(:args) { %w(whobar collection druid:ab123de4567) }
+
+      it 'access is "world"' do
+        expect(dor_registration_params[:access]).to eq({ 'access' => 'world' })
```
Comment (mjgiarlo) [inline spec/models/hydrus/generic_object_spec.rb:83]: Re: what I asked about above, plus wanting consistency with the above tests, how about this minor tweak:

```ruby
expect(dor_registration_params[:access][:access]).to eq('world')
```

:question:

**Review by mjgiarlo — APPROVED** [review]

File: app/models/hydrus/generic_object.rb (hunk 1 above)
Comment (ndushay) [reply app/models/hydrus/generic_object.rb]: suggestion taken.

File: spec/models/hydrus/generic_object_spec.rb (hunk 3 above)
Comment (ndushay) [reply spec/models/hydrus/generic_object_spec.rb]: suggestion taken.
