### PR TITLE
contact form bug

### LINKED ISSUE #150: contact form is broken
When I submit a message using the form at https://sdr.stanford.edu/contact, I get a 404 message.

### PR DESCRIPTION
**Pull request by peetucket**
fixes #150 

- fix routing for contact us page
- add tests for contact form
- fix rails 5 deprecation for mail delivery
- remove apparently unused error route

### CODE REVIEW

File: spec/features/home_page_spec.rb [hunk 1]
```diff
@@ -92,4 +92,51 @@
...
+      @name_textbox      = 'input#name'
+      @email_textbox     = 'input#email'
+      @select_menu       = 'select#subject'
+      @message_textarea  = 'textarea#message'
+      @message           = 'Hello, this is is cool.'
+      @send_button_text  = 'Send'
+      HydrusMailer.stub_chain(:contact_message, :deliver_now).and_return('a mailer')
+    end
+
+    it 'should show the full form and then generate an email when a user fills in the contact form when not logged in' do
```
Comment (jcoyne) [inline spec/features/home_page_spec.rb]: It should?   When I see that I hear "maybe it will." Can we assert "It will show..." instead?

File: config/routes.rb [hunk 2]
```diff
@@ -47,8 +47,7 @@
     get 'users/auth/webauth' => 'sessions#new', :as => 'webauth_login'
     get 'users/auth/webauth/logout' => 'sessions#destroy_webauth', :as => 'webauth_logout'
   end
-  get 'error' => 'signin#error', :as => 'error'
-  get 'contact' => 'application#contact', :as => 'contact'
+  match 'contact' => 'application#contact', :as => 'contact', via: [:get, :post]
```
Comment (jcoyne) [inline config/routes.rb]: No need to fix, but I wish this was going to ContactController instead.

File: spec/features/home_page_spec.rb [hunk 3]
```diff
@@ -92,4 +92,51 @@
...
+      logout
```
Comment (jcoyne) [inline spec/features/home_page_spec.rb]: Why are we logging out.  This hasn't logged in yet, has it?

File: spec/features/home_page_spec.rb [hunk 4]
```diff
@@ -92,4 +92,51 @@
...
+      expect(page).to have_selector(@message_textarea)
+      fill_in 'email', with: 'test@test.com'
+      fill_in 'message', with: @message
+      click_button @send_button_text
+      expect(page).to have_content 'Your message has been sent.'
+      expect(HydrusMailer).to have_received(:contact_message)
+    end
+
+    it 'should show an error message if the user does not enter a message to send' do
+      logout
```
Comment (jcoyne) [inline spec/features/home_page_spec.rb]: why are we logging out?

File: spec/features/home_page_spec.rb [hunk 5]
```diff
@@ -92,4 +92,51 @@
...
+      expect(page).to have_selector(@select_menu)
+      expect(page).to have_selector(@message_textarea)
+      fill_in 'email', with: 'test@test.com'
+      fill_in 'message', with: @message
+      click_button @send_button_text
+      expect(page).to have_content 'Your message has been sent.'
+      expect(HydrusMailer).to have_received(:contact_message)
+    end
+
+    it 'should show an error message if the user does not enter a message to send' do
```
Comment (jcoyne) [inline spec/features/home_page_spec.rb]: This to me doesn't sound like a feature, and so I wouldn't write a feature test for it. Instead I'd write a controller test.  Controller tests are much faster to run.

File: spec/features/home_page_spec.rb [hunk 6]
```diff
@@ -92,4 +92,51 @@
       expect(find(@alert)).to have_content(@sign_in_msg)
     end
   end
+
+  describe 'contact us' do
+    before(:each) do
+      @name_textbox      = 'input#name'
```
Comment (jcoyne) [inline spec/features/home_page_spec.rb]: Can you use `let` instead of instance variables.  See http://www.betterspecs.org/#let

File: spec/features/home_page_spec.rb [hunk 7]
```diff
@@ -92,4 +92,51 @@
...
+      @email_textbox     = 'input#email'
+      @select_menu       = 'select#subject'
+      @message_textarea  = 'textarea#message'
+      @message           = 'Hello, this is is cool.'
+      @send_button_text  = 'Send'
+      HydrusMailer.stub_chain(:contact_message, :deliver_now).and_return('a mailer')
```
Comment (jcoyne) [inline spec/features/home_page_spec.rb]: Deliver_now does not return anything, so there's no reason to stub its return value.

File: spec/features/home_page_spec.rb [hunk 8]
```diff
@@ -92,4 +92,51 @@
...
+
+    it 'should show an error message if the user does not enter a message to send' do
+      logout
+      visit contact_path
+      click_button @send_button_text
+      expect(page).to have_content 'Please enter message text.'
+      expect(HydrusMailer).not_to have_received(:contact_message)
+    end
+
+    it 'should show the partial form and then generate an email when a user fills in the contact form when logged in' do
```
Comment (jcoyne) [inline spec/features/home_page_spec.rb]: ~should show~ shows

File: spec/features/home_page_spec.rb (hunk 6 above)
Comment (peetucket) [reply spec/features/home_page_spec.rb]: was doing this to match what all of the other specs do and don't really want to go back and change all the specs to use let right now, do we prefer consistency or having it the preferred style in one spot?

File: spec/features/home_page_spec.rb (hunk 7 above)
Comment (peetucket) [reply spec/features/home_page_spec.rb]: ok, fixed

File: spec/features/home_page_spec.rb (hunk 1 above)
Comment (peetucket) [reply spec/features/home_page_spec.rb]: fixed

File: spec/features/home_page_spec.rb (hunk 3 above)
Comment (peetucket) [reply spec/features/home_page_spec.rb]: wasn't clear if each new test started fresh and was doing to avoid any issues with running tests in differing orders; but if each new test starts with a clean slate, this is not needed and was removed

File: spec/features/home_page_spec.rb (hunk 5 above)
Comment (peetucket) [reply spec/features/home_page_spec.rb]: don't we need to have an integration test to have access to capybara, which i am using for these tests?  leaving as is

File: config/routes.rb (hunk 2 above)
Comment (peetucket) [reply config/routes.rb]: created a new contact controller and moved tests too

File: config/routes.rb [hunk 9]
```diff
@@ -35,6 +35,9 @@
     get 'agree_to_terms_of_deposit', as: 'agree_to_terms_of_deposit', on: :collection
   end
 
+  resources :contacts
```
Comment (jcoyne) [inline config/routes.rb]: Could we do `resource :contact` here (note the singular).  Then we don't need the alias below, right?

**Comment by jcoyne** [comment]
This is looking so much better now. Just one more change and it think it's ready to ship.

File: config/routes.rb (hunk 9 above)
Comment (jcoyne) [reply config/routes.rb]: http://guides.rubyonrails.org/routing.html#singular-resources

**Comment by peetucket** [comment]
Adjusted contact routes to make it singular (had to rename main contact form action from new to show, which makes more sense anyway).
